#!/usr/bin/env python3
from __future__ import annotations

import argparse
import io
import os
from pathlib import Path

import psycopg2


SCHEMA = "today_fridge"
TABLE = "ingredient_master"


def connect():
    return psycopg2.connect(
        host=os.environ.get("PGHOST", "localhost"),
        port=os.environ.get("PGPORT", "5432"),
        user=os.environ.get("PGUSER", "postgres"),
        password=os.environ.get("PGPASSWORD", "1234"),
        dbname=os.environ.get("PGDATABASE", "today_fridge"),
    )


def fetch_columns(cur) -> list[str]:
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema=%s AND table_name=%s
        ORDER BY ordinal_position
        """,
        (SCHEMA, TABLE),
    )
    return [r[0] for r in cur.fetchall()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).parent / "sync_ingredient_master.sql",
    )
    args = ap.parse_args()

    conn = connect()
    try:
        cur = conn.cursor()
        cols = fetch_columns(cur)
        col_list = ", ".join(cols)

        buf = io.StringIO()
        # Export data in Postgres text COPY format (tab-separated, \N for NULL)
        cur.copy_expert(
            f"COPY (SELECT {col_list} FROM {SCHEMA}.{TABLE} ORDER BY ingredient_id) TO STDOUT WITH (FORMAT text)",
            buf,
        )
        data = buf.getvalue()

        # Build a robust "sync" script:
        # - Drops normalized_name UNIQUE (needed for canonical!=normalized design)
        # - Loads into temp table via COPY FROM stdin
        # - Upserts by ingredient_id
        # - Deletes rows missing from temp (exact sync)
        # - Resets sequence
        sql = f"""\
-- AUTO-GENERATED sync script for {SCHEMA}.{TABLE}
-- Generated by export_ingredient_master_sync_sql.py
--
-- Apply with:
--   psql -d today_fridge -f sync_ingredient_master.sql
--
BEGIN;

-- This design allows multiple rows to share normalized_name.
ALTER TABLE {SCHEMA}.{TABLE}
  DROP CONSTRAINT IF EXISTS ingredient_master_normalized_name_key;

CREATE TEMP TABLE tmp_{TABLE}_sync (LIKE {SCHEMA}.{TABLE} INCLUDING ALL);

COPY tmp_{TABLE}_sync ({col_list}) FROM stdin;
{data}\\.

-- Upsert (ingredient_id is primary key)
INSERT INTO {SCHEMA}.{TABLE} ({col_list})
SELECT {col_list} FROM tmp_{TABLE}_sync
ON CONFLICT (ingredient_id) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  canonical_name = EXCLUDED.canonical_name,
  normalized_name = EXCLUDED.normalized_name,
  alias_text = EXCLUDED.alias_text,
  standard_unit = EXCLUDED.standard_unit,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  embedding = EXCLUDED.embedding,
  embedding_updated_at = EXCLUDED.embedding_updated_at,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

-- Exact sync: delete rows not present in dump
DELETE FROM {SCHEMA}.{TABLE} t
WHERE NOT EXISTS (
  SELECT 1 FROM tmp_{TABLE}_sync s WHERE s.ingredient_id = t.ingredient_id
);

-- Reset sequence to max(ingredient_id)
SELECT setval(
  '{SCHEMA}.{TABLE}_ingredient_id_seq',
  COALESCE((SELECT MAX(ingredient_id) FROM {SCHEMA}.{TABLE}), 1),
  true
);

COMMIT;
"""
        args.out.write_text(sql, encoding="utf-8")
        print(f"Wrote: {args.out}")
        print(f"Rows exported (lines): {len([l for l in data.splitlines() if l.strip()])}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()

